### PR TITLE
Add episode 1 outline

### PR DESCRIPTION
**Pull request by alexyuly**

### CODE REVIEW

**Comment by TimMikeladze** [comment]
@alexyuly Thoughts on moving the majority of the implementation details to episode 2+ rather having episode 1 be more theory overview of graphql?

**Comment by alexyuly** [comment]
Yeah, it depends on the length we're going for. You think ~15 minutes like the meteor podcast?

**Comment by TimMikeladze** [comment]
@alexyuly Short and sweet, Between 15 to 30, tending to stay on the shorter side.

**Comment by alexyuly** [comment]
Merging for now. We can split the implementation pieces out into episode 2.

**Comment by alexyuly** [comment]
I don't think I have permission to merge PRs.

**Comment by TimMikeladze** [comment]
@alexyuly Thats cuase you forked. Make branches on the repo instead.

I'll merge this one,.

**Pull request merged**
